(export category "category.lisp")
(export functor "functor.lisp")
(export naturaltrans-formation "naturaltrans-formation.lisp")
(export isomorphism "isomorphism.lisp")
(export trivial-category "trivial-category.lisp")
